// src/lib/routes.ts
// Extracted from App.tsx to break circular dependency with Auth.tsx
// All application route paths live here.

export const ROUTES = {
  HOME: '/',
  PRIVACYPOLICY: '/privacy-policy',
  ABOUTUS: '/about-us',
  CONTACT: '/contact',
  BLOGS: '/blogs',
  INTEGRATIONS: '/integrations',
  TERMSOFSERVICE: '/terms-of-service',
  CAREERS: '/careers',
  API: '/api',
  DOCUMENTATIONPAGE: '/documentation-page',
  USERGUIDEPAGE: '/user-guide-page',
  AUTH: '/auth',
  RESETPASSWORD: '/reset-password',
  CALENDARCALLBACK: '/calendar-callback',
  JOIN_INVITETOKEN: '/join/:inviteToken',
  DASHBOARD: '/dashboard',
  NOTES_NOTEID_: '/notes/:noteId?',
  NOTE_NOTEID_: '/note/:noteId?',
  RECORDINGS: '/recordings',
  SCHEDULE: '/schedule',
  CHAT: '/chat',
  CHAT_SESSIONID: '/chat/:sessionId',
  DOCUMENTS: '/documents',
  SETTINGS: '/settings',
  QUIZZES: '/quizzes',
  QUIZZES_TAB: '/quizzes/:tab',
  QUIZZES_TAB_SESSIONID: '/quizzes/:tab/:sessionId',
  LIBRARY: '/library',
  LIBRARY_TAB: '/library/:tab',
  COURSE_COURSEID: '/course/:courseId',
  SUBSCRIPTION: '/subscription',
  PRICING: '/pricing',
  PODCASTS: '/podcasts',
  PODCASTS_PODCASTID: '/podcasts/:podcastId',
  PODCAST_ID: '/podcast/:id',
  PODCASTLIVE_ID: '/podcast/live/:id',
  SOCIAL: '/social',
  SOCIAL_TAB: '/social/:tab',
  SOCIALPOST_POSTID: '/social/post/:postId',
  SOCIALGROUP_GROUPID: '/social/group/:groupId',
  SOCIALPROFILE_USERID: '/social/profile/:userId',
  EDUCATORUPGRADE: '/educator/upgrade',
  EDUCATOR: '/educator',
  EDUCATORCOURSES: '/educator/courses',
  EDUCATORINSTITUTION: '/educator/institution',
  EDUCATORMEMBERS: '/educator/members',
  EDUCATORANALYTICS: '/educator/analytics',
  EDUCATORSETTINGS: '/educator/settings',
  ADMIN: '/admin',
  ADMINUSERS: '/admin/users',
  ADMINCOURSES: '/admin/courses',
  ADMINADMINS: '/admin/admins',
  ADMINMODERATION: '/admin/moderation',
  ADMINTESTIMONIALS: '/admin/testimonials',
  ADMINSETTINGS: '/admin/settings',
  ADMINLOGS: '/admin/logs',
  ADMINERRORS: '/admin/errors',
  ADMINAIINSIGHTS: '/admin/ai-insights',
  ADMINUPDATES: '/admin/updates',
  ADMINVERIFICATION: '/admin/verification',
  ADMININSTITUTIONS: '/admin/institutions',
  ADMINNOTIFICATION_ANALYTICS: '/admin/notification_analytics',
} as const;

export type AppRoute = typeof ROUTES[keyof typeof ROUTES];
