import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Loader2, Download, Send, Sparkles, Copy, Check } from 'lucide-react';
import { Button } from '../../ui/button';
import { toast } from 'sonner';
import { generateImage } from '@/services/imageGenerationService';

interface ImageGeneratorProps {
  isOpen: boolean;
  onClose: () => void;
  userId: string;
  onImageGenerated?: (imageUrl: string, prompt: string) => void;
  initialPrompt?: string;
}

export const ImageGenerator: React.FC<ImageGeneratorProps> = ({
  isOpen,
  onClose,
  userId,
  onImageGenerated,
  initialPrompt = '',
}) => {
  const [prompt, setPrompt] = useState(initialPrompt);
  const [generatedImageUrl, setGeneratedImageUrl] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [autoGeneratedOnce, setAutoGeneratedOnce] = React.useState(false);

  // Update prompt when initialPrompt changes and reset state
  React.useEffect(() => {
    if (isOpen) {
      setPrompt(initialPrompt || '');
      setGeneratedImageUrl(null);
      setAutoGeneratedOnce(false);
    }
  }, [isOpen, initialPrompt]);

  // Auto-generate if we have an initial prompt
  React.useEffect(() => {
    if (initialPrompt && isOpen && !generatedImageUrl && !isGenerating && !autoGeneratedOnce) {
      setAutoGeneratedOnce(true);
      handleGenerate();
    }
  }, [initialPrompt, isOpen, generatedImageUrl, isGenerating, autoGeneratedOnce]);

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      toast.error('Please enter a description for the image.');
      return;
    }

    setIsGenerating(true);
    try {
      const result = await generateImage(prompt, userId);
      setGeneratedImageUrl(result.imageUrl);
      toast.success('Image generated successfully!');
    } catch (error) {
      console.error('Image generation error:', error);
      toast.error(error instanceof Error ? error.message : 'Failed to generate image.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = async () => {
    if (!generatedImageUrl) return;

    try {
      const response = await fetch(generatedImageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `generated-image-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      toast.success('Image downloaded!');
    } catch (error) {
      console.error('Download error:', error);
      toast.error('Failed to download image.');
    }
  };

  const handleCopyUrl = async () => {
    if (!generatedImageUrl) return;

    try {
      await navigator.clipboard.writeText(generatedImageUrl);
      setCopied(true);
      toast.success('Image URL copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Copy error:', error);
      toast.error('Failed to copy URL.');
    }
  };

  const handleSendToChat = () => {
    if (!generatedImageUrl) return;
    if (onImageGenerated) {
      onImageGenerated(generatedImageUrl, prompt);
      toast.success('Image added to chat!');
      handleClose();
    }
  };

  const handleClose = () => {
    setPrompt('');
    setGeneratedImageUrl(null);
    setIsGenerating(false);
    onClose();
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleGenerate();
    }
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50"
            onClick={handleClose}
          />

          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl w-full max-w-3xl max-h-[90vh] overflow-hidden flex flex-col">
              {/* Header */}
              <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-gradient-to-br from-purple-500 to-pink-500 rounded-lg">
                    <Sparkles className="h-5 w-5 text-white" />
                  </div>
                  <div>
                    <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                      AI Image Generator
                    </h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Powered by Google Gemini
                    </p>
                  </div>
                </div>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={handleClose}
                  className="rounded-full hover:bg-gray-100 dark:hover:bg-gray-700"
                >
                  <X className="h-5 w-5" />
                </Button>
              </div>

              {/* Content */}
              <div className="flex-1 overflow-y-auto p-6 space-y-6">
                {/* Prompt Input */}
                <div className="space-y-2">
                  <label className="text-sm font-medium text-gray-700 dark:text-gray-300">
                    Describe the image you want to generate
                  </label>
                  <div className="relative">
                    <textarea
                      value={prompt}
                      onChange={(e) => setPrompt(e.target.value)}
                      onKeyDown={handleKeyDown}
                      placeholder="E.g., A futuristic city at sunset with flying cars and neon lights..."
                      className="w-full min-h-[120px] px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 resize-none"
                      disabled={isGenerating}
                    />
                    <div className="absolute bottom-3 right-3 text-xs text-gray-400">
                      Press Enter to generate
                    </div>
                  </div>
                </div>

                {/* Generate Button */}
                {!generatedImageUrl && (
                  <Button
                    onClick={handleGenerate}
                    disabled={isGenerating || !prompt.trim()}
                    className="w-full bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white py-6 rounded-lg font-medium text-lg shadow-lg transition-all duration-200"
                  >
                    {isGenerating ? (
                      <>
                        <Loader2 className="h-5 w-5 mr-2 animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-5 w-5 mr-2" />
                        Generate Image
                      </>
                    )}
                  </Button>
                )}

                {/* Loading State */}
                {isGenerating && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="flex flex-col items-center justify-center py-12 space-y-4"
                  >
                    <div className="relative">
                      <div className="h-20 w-20 rounded-full border-4 border-purple-200 dark:border-purple-900"></div>
                      <div className="absolute top-0 left-0 h-20 w-20 rounded-full border-4 border-purple-500 border-t-transparent animate-spin"></div>
                    </div>
                    <p className="text-gray-600 dark:text-gray-400 animate-pulse">
                      Creating your masterpiece...
                    </p>
                  </motion.div>
                )}

                {/* Generated Image */}
                {generatedImageUrl && !isGenerating && (
                  <motion.div
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="space-y-4"
                  >
                    <div className="relative group rounded-lg overflow-hidden bg-gray-100 dark:bg-gray-900">
                      <img
                        src={generatedImageUrl}
                        alt={prompt}
                        className="w-full h-auto max-h-96 object-contain"
                      />
                      <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors duration-200"></div>
                    </div>

                    {/* Action Buttons */}
                    <div className="grid grid-cols-2 gap-3">
                      <Button
                        onClick={handleDownload}
                        variant="outline"
                        className="flex items-center justify-center gap-2"
                      >
                        <Download className="h-4 w-4" />
                        Download
                      </Button>
                      <Button
                        onClick={handleCopyUrl}
                        variant="outline"
                        className="flex items-center justify-center gap-2"
                      >
                        {copied ? (
                          <>
                            <Check className="h-4 w-4 text-green-500" />
                            Copied!
                          </>
                        ) : (
                          <>
                            <Copy className="h-4 w-4" />
                            Copy URL
                          </>
                        )}
                      </Button>
                    </div>

                    {onImageGenerated && (
                      <Button
                        onClick={handleSendToChat}
                        className="w-full bg-blue-600 hover:bg-blue-700 text-white"
                      >
                        <Send className="h-4 w-4 mr-2" />
                        Send to Chat
                      </Button>
                    )}

                    {/* Generate Another */}
                    <Button
                      onClick={() => {
                        setGeneratedImageUrl(null);
                        setPrompt('');
                      }}
                      variant="ghost"
                      className="w-full"
                    >
                      Generate Another Image
                    </Button>
                  </motion.div>
                )}
              </div>

              {/* Footer with tips */}
              {!generatedImageUrl && !isGenerating && (
                <div className="px-6 py-4 bg-gray-50 dark:bg-gray-900/50 border-t border-gray-200 dark:border-gray-700">
                  <p className="text-xs text-gray-500 dark:text-gray-400">
                    💡 Tip: Be specific with your descriptions for better results. Include details about
                    style, colors, mood, and composition.
                  </p>
                </div>
              )}
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
};
